# Generated by Django 5.2.5 on 2025-09-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('project_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='customers',
            field=models.ManyToManyField(blank=True, related_name='teams', to='project_management.customer'),
        ),
    ]
