[project]
name = "frontend"
version = "0.19.2"
description = "Ixora-RAG-Project, this help user to communicate with documents."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "streamlit>=1.50.0",
    "streamlit",
    "requests",
    "langchain-core",
    "pandas>=2.3.3",
]
