# Generated by Django 5.2.5 on 2025-09-19 07:22

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0002_documentembedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentembedding',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=384),
        ),
    ]
