# Generated by Django 5.2.5 on 2025-09-19 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0003_alter_documentembedding_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentembedding',
            name='created_at',
        ),
    ]
