# Generated by Django 5.2.5 on 2025-09-19 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0004_remove_documentembedding_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentembedding',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_management.customer'),
        ),
        migrations.AddField(
            model_name='documentembedding',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project_management.tag'),
        ),
    ]
