# Generated by Django 5.2.5 on 2025-09-20 03:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0005_documentembedding_customer_documentembedding_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentembedding',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='documentembedding',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
