# Generated by Django 5.2.5 on 2025-09-20 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0006_remove_documentembedding_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentembedding',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
