# Generated by Django 5.2.5 on 2025-09-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0007_alter_documentembedding_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentembedding',
            name='chunk_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
