# Generated by Django 5.2.5 on 2025-09-24 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0008_documentembedding_chunk_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentembedding',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='project_management.document'),
        ),
    ]
