# Generated by Django 5.2.5 on 2025-10-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0009_alter_documentembedding_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentembedding',
            name='page_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentembedding',
            name='parent_chunk_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentembedding',
            name='section_title',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
