# Generated by Django 5.2.7 on 2025-10-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0010_documentembedding_page_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_query', models.TextField()),
                ('response', models.TextField()),
                ('provider', models.CharField(max_length=50)),
                ('context_snippet', models.TextField(blank=True, null=True)),
                ('context_match_count', models.IntegerField(default=0)),
                ('sources', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
