# Generated by Django 5.2.7 on 2025-10-13 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_team_customers'),
        ('project_management', '0011_querylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustomerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tags', to='project_management.customer')),
                ('role', models.ForeignKey(default='viewer', on_delete=django.db.models.deletion.CASCADE, to='api.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'customer')},
            },
        ),
        migrations.DeleteModel(
            name='UserTagAssignment',
        ),
    ]
