# Generated by Django 5.2.7 on 2025-10-13 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_team_customers'),
        ('project_management', '0012_usercustomerassignment_delete_usertagassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomerassignment',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='api.role'),
        ),
    ]
