# Generated by Django 5.2.7 on 2025-10-13 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_team_customers'),
        ('project_management', '0013_alter_usercustomerassignment_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercustomerassignment',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='customer',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='project_management.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='provider',
            field=models.CharField(default='phi3', max_length=50),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='initial_customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='initial_chat_sessions', to='project_management.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercustomerassignment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role_assignments', to='project_management.customer'),
        ),
        migrations.AlterField(
            model_name='usercustomerassignment',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role_assignments', to='api.role'),
        ),
        migrations.AlterField(
            model_name='usercustomerassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_role_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
