# Generated by Django 5.2.7 on 2025-10-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0014_alter_usercustomerassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='provider',
            field=models.CharField(default='llama', max_length=50),
        ),
    ]
